<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;
use common\models\PaymentMethod;

$this->title = 'Pay Securely';
$this->params['breadcrumbs'][] = $this->title;
?>

<!-- ==============================================
	 Header
	 =============================================== -->	 
     <header class="header-jobs">
      <div class="container">
	   <div class="content">
	    
       </div><!-- /.content -->
	  </div><!-- /.container -->
     </header><!-- /header -->
	 
     <!-- ==============================================
	 Jobs Section
	 =============================================== -->
<section class="jobslist">
	  <div class="container">
	   <div class="row-fluid">
	   
	    <div class="col-lg-2">
		</div><!-- /.col-lg-2 -->
	    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 white">
	    
		  <div class="job">	
		  <div class="row top-sec">
		   <div class="col-lg-12">		   
			<div class="col-lg-12 col-xs-12">
			<?php
                include_once('OAuth.php');
                
                //pesapal params
                $token = $params = NULL;
                
                /*
                PesaPal Sandbox is at http://demo.pesapal.com. Use this to test your developement and 
                when you are ready to go live change to https://www.pesapal.com.
                */
                $consumer_key = $data['consumer_key'];//Register a merchant account on
                                   //demo.pesapal.com and use the merchant key for testing.
                                   //When you are ready to go live make sure you change the key to the live account
                                   //registered on www.pesapal.com!
                $consumer_secret = $data['consumer_secret'];// Use the secret from your test
                                   //account on demo.pesapal.com. When you are ready to go live make sure you 
                                   //change the secret to the live account registered on www.pesapal.com!
                $signature_method = new OAuthSignatureMethod_HMAC_SHA1();
                $iframelink = $data['iframelink'];//change to      
                                   //https://www.pesapal.com/API/PostPesapalDirectOrderV4 when you are ready to go live!
                
                //get form details
                $amount = $data['amount']; //$_POST['amount'];
                $amount = number_format($amount, 2);//format amount to 2 decimal places
                
                $desc = $data['desc']; //$_POST['description'];
                $type = $data['type']; //$_POST['type']; //default value = MERCHANT
                $reference = $data['reference']; //$_POST['reference'];//unique order id of the transaction, generated by merchant
                $first_name = $data['first_name']; //$_POST['first_name'];
                $last_name = $data['last_name']; //$_POST['last_name'];
                $email = $data['email']; //$_POST['email'];
                $phonenumber = $data['phonenumber'];//ONE of email or phonenumber is required
                
                $callback_url = $data['callback_url']; //redirect url, the page that will handle the response from pesapal.
                
                $post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?><PesapalDirectOrderInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" Amount=\"".$amount."\" Description=\"".$desc."\" Type=\"".$type."\" Reference=\"".$reference."\" FirstName=\"".$first_name."\" LastName=\"".$last_name."\" Email=\"".$email."\" PhoneNumber=\"".$phonenumber."\" xmlns=\"http://www.pesapal.com\" />";
                $post_xml = htmlentities($post_xml);
                
                $consumer = new OAuthConsumer($consumer_key, $consumer_secret);
                
                //post transaction to pesapal
                $iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
                $iframe_src->set_parameter("oauth_callback", $callback_url);
                $iframe_src->set_parameter("pesapal_request_data", $post_xml);
                $iframe_src->sign_request($signature_method, $consumer, $token);
                
                //display pesapal - iframe and pass iframe_src
             ?>
                <iframe src="<?php echo $iframe_src;?>" width="100%" height="700px"  scrolling="no" frameBorder="0">
                	<p>Browser unable to load iFrame</p>
                </iframe>
			<br>		
		    </div><!-- /.col-lg-12 -->
		   </div><!-- /.row -->
		  </div>
		 </div>
	    </div><!-- /.col-lg-8 -->
	   </div><!-- /.row -->
	  </div><!-- /.container-fluid -->
     </section><!-- /section --> 
     <br><br>